/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function subtract(a: number, b: number): number
export function divide(a: number, b: number): number
export function multiply(a: number, b: number): number
export function modulus(a: number, b: number): number
